using System.ComponentModel.DataAnnotations;

using System;
using System.ComponentModel.DataAnnotations;

namespace Estately.Services.ViewModels
{
    public class PropertyViewModel
    {
        public int PropertyID { get; set; }

        [Required(ErrorMessage = "Developer Profile is required")]
        [Display(Name = "Developer Profile")]
        public int DeveloperProfileID { get; set; }

        [Required(ErrorMessage = "Property Type is required")]
        [Display(Name = "Property Type")]
        public int PropertyTypeID { get; set; }

        [Required(ErrorMessage = "Status is required")]
        [Display(Name = "Status")]
        public int StatusId { get; set; }

        [Required(ErrorMessage = "Zone is required")]
        [Display(Name = "Zone")]
        public int ZoneID { get; set; }

        [StringLength(255)]
        public string? Title { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [StringLength(255)]
        public string Address { get; set; } = string.Empty;

        [Required(ErrorMessage = "Price is required")]
        [Range(0, double.MaxValue, ErrorMessage = "Price must be greater than 0")]
        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [StringLength(500)]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Area is required")]
        [Range(0, double.MaxValue, ErrorMessage = "Area must be greater than 0")]
        [Display(Name = "Area")]
        public decimal Area { get; set; }

        [Display(Name = "Listing Date")]
        public DateTime ListingDate { get; set; } = DateTime.Now;

        [Display(Name = "Expected Rent Price")]
        public decimal? ExpectedRentPrice { get; set; }

        [Display(Name = "Is Deleted")]
        public bool? IsDeleted { get; set; } = false;

        [Display(Name = "Agent")]
        public int? AgentId { get; set; }

        // YearBuilt is REQUIRED now (non-nullable)
        [Required(ErrorMessage = "Year Built is required")]
        [Display(Name = "Year Built")]
        public int YearBuilt { get; set; }

        [Required(ErrorMessage = "Floors Number is required")]
        [Display(Name = "Floors Number")]
        public int FloorsNo { get; set; }

        [Required(ErrorMessage = "Beds Number is required")]
        [Display(Name = "Beds Number")]
        public int BedsNo { get; set; }

        [Required(ErrorMessage = "Baths Number is required")]
        [Display(Name = "Baths Number")]
        public int BathsNo { get; set; }

        [Required(ErrorMessage = "Latitude is required")]
        [Display(Name = "Latitude")]
        public decimal Latitude { get; set; }

        [Required(ErrorMessage = "Longitude is required")]
        [Display(Name = "Longitude")]
        public decimal Longitude { get; set; }

        [Display(Name = "Is Furnished")]
        public bool? IsFurnished { get; set; } = false;

        // PropertyCode will be generated by the service - keep it read-only in UI
        [Display(Name = "Property Code")]
        public string PropertyCode { get; set; } = string.Empty;

        // Navigation properties for display (read-only)
        [Display(Name = "Developer Name")]
        public string? DeveloperName { get; set; }

        [Display(Name = "Agent Name")]
        public string? AgentName { get; set; }

        [Display(Name = "Property Type")]
        public string? PropertyTypeName { get; set; }

        [Display(Name = "Status")]
        public string? StatusName { get; set; }

        [Display(Name = "Zone")]
        public string? ZoneName { get; set; }
    }

public class PropertyListViewModel : BaseViewModel
    {
        public List<PropertyViewModel> Properties { get; set; } = new();
        public List<LkpPropertyTypeViewModel> PropertyTypes { get; set; } = new();
        public List<LkpPropertyStatusViewModel> PropertyStatuses { get; set; } = new();
        public List<DeveloperProfileViewModel> DeveloperProfiles { get; set; } = new();
        public List<ZonesViewModel> Zones { get; set; } = new();
    }
}

