// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{

    [Table("TblPropertyStatus")]
    public partial class LkpPropertyStatus
    {
        [Key]
        public int StatusID { get; set; }

        [Required]
        [StringLength(255)]
        public string StatusName { get; set; }

        [StringLength(255)]
        public string Description { get; set; }

        [InverseProperty("Status")]
        public virtual TblProperty TblProperty { get; set; }
    }
}