// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[Table("LkpPropertyStatus")]
public partial class LkpPropertyStatus
{
    [Key]
    public int StatusID { get; set; }

    [Required]
    [StringLength(255)]
    public string StatusName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();
}