// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblAppointment
{
    [Key]
    public int AppointmentID { get; set; }

    public int PropertyID { get; set; }

    public int EmployeeClientID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AppointmentDate { get; set; }

    [Required]
    [StringLength(255)]
    public string Status { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    [ForeignKey("EmployeeClientID")]
    [InverseProperty("TblAppointments")]
    public virtual TblEmployeeClient EmployeeClient { get; set; }

    [ForeignKey("PropertyID")]
    [InverseProperty("TblAppointments")]
    public virtual TblProperty Property { get; set; }
}