// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblAppointment
    {
        [Key]
        public int AppointmentID { get; set; }
        [Required]
        public int PropertyID { get; set; }
        [Required]
        public int EmployeeClientID { get; set; }

        [Required]
        [Column(TypeName = "datetime")]
        public DateTime AppointmentDate { get; set; }

        [Required]
        [StringLength(255)]
        public string Status { get; set; }

        [Column(TypeName = "text")]
        public string Notes { get; set; }

        [ForeignKey("EmployeeClientID")]
        [InverseProperty("TblAppointments")]
        public virtual TblEmployeeClient EmployeeClient { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblAppointments")]
        public virtual TblProperty Property { get; set; }
    }
}