// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblBranch
{
    [Key]
    public int BranchID { get; set; }

    [Required]
    [StringLength(255)]
    public string BranchName { get; set; }

    [Required]
    [StringLength(10)]
    public string ManagerName { get; set; }

    [Required]
    [StringLength(255)]
    public string Address { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Phone { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<TblDepartment> TblDepartments { get; set; } = new List<TblDepartment>();
}