// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblClientProfile
    {
        [Key]
        public int ClientProfileID { get; set; }

        [Required]
        public int UserID { get; set; }

        [Required]
        [StringLength(255)]
        public string ClientName { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)] 
        public string Phone { get; set; }

        [InverseProperty("ClientProfile")]
        public virtual ICollection<TblEmployeeClient> TblEmployeeClients { get; set; } = new List<TblEmployeeClient>();

        [InverseProperty("ClientProfile")]
        public virtual ICollection<TblFavorite> TblFavorites { get; set; } = new List<TblFavorite>();
    }
}