// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblCity
{
    [Key]
    public int CityID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string CityName { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<TblZone> TblZones { get; set; } = new List<TblZone>();
}