// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [Table("TblCommission")]
    public partial class TblCommission
    {
        [Key]
        public int CommissionID { get; set; }

        [Required]
        public int TransactionID { get; set; }

        [Required]
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime PaidDate { get; set; } = DateTime.Now;

        [ForeignKey("TransactionID")]
        [InverseProperty("TblCommissions")]
        public virtual TblTransaction Transaction { get; set; }
    }
}