// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

[Table("TblCommission")]
public partial class TblCommission
{
    [Key]
    public int CommissionID { get; set; }

    public int TransactionID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PaidDate { get; set; }

    [ForeignKey("TransactionID")]
    [InverseProperty("TblCommissions")]
    public virtual TblTransaction Transaction { get; set; }
}