// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{
    public partial class TblDocumentType
    {
        [Key]
        public int DocumentTypeID { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(255)]
        public string Description { get; set; }

        [InverseProperty("DocumentType")]
        public virtual ICollection<TblPropertyDocument> TblPropertyDocuments { get; set; } = new List<TblPropertyDocument>();
    }
}