// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblDepartment
    {
        [Key]
        public int DepartmentID { get; set; }

        [Required]
        public int BranchId { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string DepartmentName { get; set; }

        [StringLength(100)]
        public string ManagerName { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }

        [ForeignKey("BranchId")]
        [InverseProperty("TblDepartments")]
        public virtual TblBranch Branch { get; set; }

        [InverseProperty("Department")]
        public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
    }
}