// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblDeveloperProfile
{
    [Key]
    public int DeveloperProfileID { get; set; }

    public int UserID { get; set; }

    [Required]
    [StringLength(255)]
    public string DeveloperName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string WebsiteURL { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string LogoURL { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [InverseProperty("DeveloperProfile")]
    public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();
}