// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblDepartment
{
    [Key]
    public int DepartmentID { get; set; }

    public int BranchId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string DepartmentName { get; set; }

    [StringLength(10)]
    public string ManagerName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("TblDepartments")]
    public virtual TblBranch Branch { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
}