// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblDeveloperProfile
    {
        [Key]
        public int DeveloperProfileID { get; set; }

        [Required]
        public int UserID { get; set; }

        [Required]
        [StringLength(255)]
        public string DeveloperName { get; set; }

        [StringLength(255)]
        [Unicode(false)]
        public string WebsiteURL { get; set; }

        [StringLength(255)]
        [Unicode(false)]
        public string LogoURL { get; set; }

        [Required]
        [StringLength(50)]
        public string Phone { get; set; }

        [InverseProperty("DeveloperProfile")]
        public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();
    }
}