// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{

    public partial class TblDepartment
    {
        [Key]
        public int DepartmentID { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string DepartmentName { get; set; }

        [StringLength(100)]
        public string ManagerName { get; set; }

        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }

        [InverseProperty("Department")]
        public virtual ICollection<TblBranchDepartment> TblBranchDepartments { get; set; } = new List<TblBranchDepartment>();

        [InverseProperty("Department")]
        public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
    }
}