// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

[Index("UserID", Name = "IX_TblEmployees", IsUnique = true)]
public partial class TblEmployee
{
    [Key]
    public int EmployeeID { get; set; }

    public int UserID { get; set; }

    public int DepartmentID { get; set; }

    [StringLength(255)]
    public string ManagerName { get; set; }

    [Required]
    [StringLength(255)]
    public string EmployeeName { get; set; }

    [Required]
    [StringLength(50)]
    public string Gender { get; set; }

    [Required]
    [StringLength(50)]
    public string Age { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Required]
    [StringLength(255)]
    public string JobTitle { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Salary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime HireDate { get; set; }

    public bool isActive { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("TblEmployees")]
    public virtual TblDepartment Department { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<TblEmployeeClient> TblEmployeeClients { get; set; } = new List<TblEmployeeClient>();

    [ForeignKey("UserID")]
    [InverseProperty("TblEmployee")]
    public virtual TblUser User { get; set; }
}