// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblEmployeeClient
{
    [Key]
    public int EmployeeClientID { get; set; }

    public int EmployeeID { get; set; }

    public int ClientProfileID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AssignmentDate { get; set; }

    [ForeignKey("ClientProfileID")]
    [InverseProperty("TblEmployeeClients")]
    public virtual TblClientProfile ClientProfile { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("TblEmployeeClients")]
    public virtual TblEmployee Employee { get; set; }

    [InverseProperty("EmployeeClient")]
    public virtual ICollection<TblAppointment> TblAppointments { get; set; } = new List<TblAppointment>();

    [InverseProperty("EmployeeClient")]
    public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
}