// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblEmployeeClient
    {
        [Key]
        public int EmployeeClientID { get; set; }
        [Required]
        public int EmployeeID { get; set; }
        [Required]
        public int ClientProfileID { get; set; }

        [Required]
        [Column(TypeName = "datetime")]
        public DateTime? AssignmentDate { get; set; } = DateTime.Now;

        [ForeignKey("ClientProfileID")]
        [InverseProperty("TblEmployeeClients")]
        public virtual TblClientProfile ClientProfile { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("TblEmployeeClients")]
        public virtual TblEmployee Employee { get; set; }

        [InverseProperty("EmployeeClient")]
        public virtual ICollection<TblAppointment> TblAppointments { get; set; } = new List<TblAppointment>();

        [InverseProperty("EmployeeClient")]
        public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
    }
}