// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblFavorite
    {
        [Key]
        public int FavoriteID { get; set; }
        [Required]
        public int ClientProfileID { get; set; }
        [Required]
        public int PropertyID { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }

        public bool IsDeleted { get; set; } = false;

        [ForeignKey("ClientProfileID")]
        [InverseProperty("TblFavorites")]
        public virtual TblClientProfile ClientProfile { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblFavorites")]
        public virtual TblProperty Property { get; set; }
    }
}