// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

public partial class TblJobTitle
{
    [Key]
    public int JobTitleId { get; set; }

    [Required]
    [StringLength(255)]
    public string JobTitleName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [InverseProperty("JobTitle")]
    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
}