// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblPropertyType
{
    [Key]
    public int PropertyTypeID { get; set; }

    [Required]
    [StringLength(255)]
    public string Type { get; set; }

    [InverseProperty("PropertyType")]
    public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();
}