// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[PrimaryKey("PropertyID", "FeatureID")]
[Table("TblPropertyFeaturesMapping")]
[Index("FeatureID", Name = "IX_TblPropertyFeaturesMapping_FeatureID")]
public partial class TblPropertyFeaturesMapping
{
    [Key]
    public int PropertyID { get; set; }

    [Key]
    public int FeatureID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Value { get; set; }

    [ForeignKey("FeatureID")]
    [InverseProperty("TblPropertyFeaturesMappings")]
    public virtual TblPropertyFeature Feature { get; set; }

    [ForeignKey("PropertyID")]
    [InverseProperty("TblPropertyFeaturesMappings")]
    public virtual TblProperty Property { get; set; }
}