// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{

    [Table("TblPropertyHistory")]
    public partial class TblPropertyHistory
    {
        [Key]
        public int HistoryID { get; set; }

        public int PropertyID { get; set; }

        public int? UserID { get; set; }

        public int HistoryTypeID { get; set; }

        public string OldValue { get; set; }

        public string NewValue { get; set; }

        public string Notes { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }

        [ForeignKey("HistoryTypeID")]
        [InverseProperty("TblPropertyHistories")]
        public virtual LKPPropertyHistoryType HistoryType { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyHistories")]
        public virtual TblProperty Property { get; set; }

        [ForeignKey("UserID")]
        [InverseProperty("TblPropertyHistories")]
        public virtual TblUser User { get; set; }
    }
}