// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblPropertyImage
    {
        [Key]
        public int ImageID { get; set; }

        [Required]
        public int PropertyID { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ImagePath { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime UploadedDate { get; set; } = DateTime.Now;

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyImages")]
        public virtual TblProperty Property { get; set; }
    }
}