// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblPropertyImage
{
    [Key]
    public int ImageID { get; set; }

    public int PropertyID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ImagePath { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UploadedDate { get; set; }

    [ForeignKey("PropertyID")]
    [InverseProperty("TblPropertyImages")]
    public virtual TblProperty Property { get; set; }
}