// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

public partial class TblPropertyFeature
{
    [Key]
    public int FeatureID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string FeatureName { get; set; }

    [StringLength(800)]
    public string Description { get; set; }

    public bool? IsAmenity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Feature")]
    public virtual ICollection<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; } = new List<TblPropertyFeaturesMapping>();
}