// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblProperty
    {
        [Key]
        public int PropertyID { get; set; }

        [Required]
        public int DeveloperProfileID { get; set; }

        [Required]
        public int PropertyTypeID { get; set; }

        [Required]
        public int ZoneID { get; set; }

        [Required]
        [StringLength(255)]
        public string Title { get; set; }

        [Required]
        [StringLength(255)]
        public string Address { get; set; }

        [Required]
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Price { get; set; }

        [Required]
        [StringLength(500)]
        public string Description { get; set; }

        [Required]
        [StringLength(255)]
        public string Area { get; set; }

        [Required]
        public bool IsSold { get; set; } = false;

        [Required]
        [Column(TypeName = "datetime")]
        public DateTime ListingDate { get; set; } = DateTime.Now;

        [ForeignKey("DeveloperProfileID")]
        [InverseProperty("TblProperties")]
        public virtual TblDeveloperProfile DeveloperProfile { get; set; }

        [ForeignKey("PropertyTypeID")]
        [InverseProperty("TblProperties")]
        public virtual TblPropertyType PropertyType { get; set; }

        [InverseProperty("Property")]
        public virtual ICollection<TblAppointment> TblAppointments { get; set; } = new List<TblAppointment>();

        [InverseProperty("Property")]
        public virtual ICollection<TblFavorite> TblFavorites { get; set; } = new List<TblFavorite>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; } = new List<TblPropertyFeaturesMapping>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyImage> TblPropertyImages { get; set; } = new List<TblPropertyImage>();

        [InverseProperty("Property")]
        public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();

        [ForeignKey("ZoneID")]
        [InverseProperty("TblProperties")]
        public virtual TblZone Zone { get; set; }
    }
}