// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [PrimaryKey("PropertyID", "FeatureID")]
    [Table("TblPropertyFeaturesMapping")]
    public partial class TblPropertyFeaturesMapping
    {
        [Key]
        public int PropertyID { get; set; }

        [Key]
        public int FeatureID { get; set; }

        [StringLength(255)]
        [Unicode(false)]
        public string Value { get; set; }

        [ForeignKey("FeatureID")]
        [InverseProperty("TblPropertyFeaturesMappings")]
        public virtual TblPropertyFeature Feature { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyFeaturesMappings")]
        public virtual TblProperty Property { get; set; }
    }
}