// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{
    public partial class TblPropertyFeature
    {
        [Key]
        public int FeatureID { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string FeatureName { get; set; }

        [Column(TypeName = "text")]
        public string Description { get; set; }

        [InverseProperty("Feature")]
        public virtual ICollection<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; } = new List<TblPropertyFeaturesMapping>();
    }
}