// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{

    [Index("StatusId", Name = "IX_TblProperties", IsUnique = true)]
    [Index("DeveloperProfileID", Name = "IX_TblProperties_DeveloperProfileID")]
    [Index("PropertyTypeID", Name = "IX_TblProperties_PropertyTypeID")]
    [Index("ZoneID", Name = "IX_TblProperties_ZoneID")]
    public partial class TblProperty
    {
        [Key]
        public int PropertyID { get; set; }

        public int DeveloperProfileID { get; set; }

        public int PropertyTypeID { get; set; }

        public int StatusId { get; set; }

        public int ZoneID { get; set; }

        [Required]
        [StringLength(255)]
        public string Title { get; set; }

        [Required]
        [StringLength(255)]
        public string Address { get; set; }

        [Column(TypeName = "decimal(10, 2)")]
        public decimal Price { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [Column(TypeName = "decimal(10, 2)")]
        public decimal Area { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime ListingDate { get; set; }

        [Column(TypeName = "decimal(10, 2)")]
        public decimal? ExpectedRentPrice { get; set; }

        public bool? IsDeleted { get; set; }

        [ForeignKey("DeveloperProfileID")]
        [InverseProperty("TblProperties")]
        public virtual TblDeveloperProfile DeveloperProfile { get; set; }

        [ForeignKey("PropertyTypeID")]
        [InverseProperty("TblProperties")]
        public virtual LkpPropertyType PropertyType { get; set; }

        [ForeignKey("StatusId")]
        [InverseProperty("TblProperty")]
        public virtual LkpPropertyStatus Status { get; set; }

        [InverseProperty("Property")]
        public virtual ICollection<TblAppointment> TblAppointments { get; set; } = new List<TblAppointment>();

        [InverseProperty("Property")]
        public virtual ICollection<TblFavorite> TblFavorites { get; set; } = new List<TblFavorite>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyDocument> TblPropertyDocuments { get; set; } = new List<TblPropertyDocument>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; } = new List<TblPropertyFeaturesMapping>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyHistory> TblPropertyHistories { get; set; } = new List<TblPropertyHistory>();

        [InverseProperty("Property")]
        public virtual ICollection<TblPropertyImage> TblPropertyImages { get; set; } = new List<TblPropertyImage>();

        [ForeignKey("ZoneID")]
        [InverseProperty("TblProperties")]
        public virtual TblZone Zone { get; set; }
    }
}