// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblPayment
{
    [Key]
    public int PaymentID { get; set; }

    public int TransactionID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PaymentDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PaymentMethod { get; set; }

    [ForeignKey("TransactionID")]
    [InverseProperty("TblPayments")]
    public virtual TblTransaction Transaction { get; set; }
}