// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblTransaction
    {
        [Key]
        public int TransactionID { get; set; }
        [Required]
        public int PropertyID { get; set; }

        [Required]
        public int EmployeeClientID { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string TransactionType { get; set; }

        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string FileURL { get; set; }

        [Required]
        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [ForeignKey("EmployeeClientID")]
        [InverseProperty("TblTransactions")]
        public virtual TblEmployeeClient EmployeeClient { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblTransactions")]
        public virtual TblProperty Property { get; set; }

        [InverseProperty("Transaction")]
        public virtual ICollection<TblCommission> TblCommissions { get; set; } = new List<TblCommission>();

        [InverseProperty("Transaction")]
        public virtual ICollection<TblPayment> TblPayments { get; set; } = new List<TblPayment>();
    }
}