// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblUser
    {
        [Key]
        public int UserID { get; set; }

        [Required]
        public int UserTypeID { get; set; }

        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }

        [Required]
        [StringLength(255)]
        public string Username { get; set; }

        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string PasswordHash { get; set; }

        public bool IsEmployee { get; set; }

        public bool ISClient { get; set; } = true;

        public bool IsDeveloper { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public bool IsDeleted { get; set; } = false;

        [InverseProperty("User")]
        public virtual TblEmployee TblEmployee { get; set; }

        [ForeignKey("UserTypeID")]
        [InverseProperty("TblUsers")]
        public virtual TblUserType UserType { get; set; }
    }
}