// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblUser
{
    [Key]
    public int UserID { get; set; }

    public int UserTypeID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string Username { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    public bool IsEmployee { get; set; }

    public bool ISClient { get; set; }

    public bool IsDeveloper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("User")]
    public virtual TblEmployee TblEmployee { get; set; }

    [ForeignKey("UserTypeID")]
    [InverseProperty("TblUsers")]
    public virtual TblUserType UserType { get; set; }
}