// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure;

public partial class TblZone
{
    [Key]
    public int ZoneID { get; set; }

    public int CityID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ZoneName { get; set; }

    [ForeignKey("CityID")]
    [InverseProperty("TblZones")]
    public virtual TblCity City { get; set; }

    [InverseProperty("Zone")]
    public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();
}