// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Infrastructure.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext() {}

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options) {}

        public virtual DbSet<TblAppointment> TblAppointments { get; set; }

        public virtual DbSet<TblBranch> TblBranches { get; set; }

        public virtual DbSet<TblCity> TblCities { get; set; }

        public virtual DbSet<TblClientProfile> TblClientProfiles { get; set; }

        public virtual DbSet<TblCommission> TblCommissions { get; set; }

        public virtual DbSet<TblDepartment> TblDepartments { get; set; }

        public virtual DbSet<TblDeveloperProfile> TblDeveloperProfiles { get; set; }

        public virtual DbSet<TblEmployee> TblEmployees { get; set; }

        public virtual DbSet<TblEmployeeClient> TblEmployeeClients { get; set; }

        public virtual DbSet<TblFavorite> TblFavorites { get; set; }

        public virtual DbSet<TblPayment> TblPayments { get; set; }

        public virtual DbSet<TblProperty> TblProperties { get; set; }

        public virtual DbSet<TblPropertyFeature> TblPropertyFeatures { get; set; }

        public virtual DbSet<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; }

        public virtual DbSet<TblPropertyImage> TblPropertyImages { get; set; }

        public virtual DbSet<TblPropertyType> TblPropertyTypes { get; set; }

        public virtual DbSet<TblTransaction> TblTransactions { get; set; }

        public virtual DbSet<TblUser> TblUsers { get; set; }

        public virtual DbSet<TblUserType> TblUserTypes { get; set; }

        public virtual DbSet<TblZone> TblZones { get; set; }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
