// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Estately.Infrastructure.Data {

    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LKPPropertyHistoryType> LKPPropertyHistoryTypes { get; set; }

        public virtual DbSet<TblAppointment> TblAppointments { get; set; }

        public virtual DbSet<TblAppointmentStatus> TblAppointmentStatuses { get; set; }

        public virtual DbSet<TblBranch> TblBranches { get; set; }

        public virtual DbSet<TblBranchDepartment> TblBranchDepartments { get; set; }

        public virtual DbSet<TblCity> TblCities { get; set; }

        public virtual DbSet<TblClientProfile> TblClientProfiles { get; set; }

        public virtual DbSet<TblDepartment> TblDepartments { get; set; }

        public virtual DbSet<TblDeveloperProfile> TblDeveloperProfiles { get; set; }

        public virtual DbSet<TblDocumentType> TblDocumentTypes { get; set; }

        public virtual DbSet<TblEmployee> TblEmployees { get; set; }

        public virtual DbSet<TblEmployeeClient> TblEmployeeClients { get; set; }

        public virtual DbSet<TblFavorite> TblFavorites { get; set; }

        public virtual DbSet<TblProperty> TblProperties { get; set; }

        public virtual DbSet<TblPropertyDocument> TblPropertyDocuments { get; set; }

        public virtual DbSet<TblPropertyFeature> TblPropertyFeatures { get; set; }

        public virtual DbSet<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; }

        public virtual DbSet<TblPropertyHistory> TblPropertyHistories { get; set; }

        public virtual DbSet<TblPropertyImage> TblPropertyImages { get; set; }

        public virtual DbSet<TblPropertyStatus> TblPropertyStatuses { get; set; }

        public virtual DbSet<TblPropertyType> TblPropertyTypes { get; set; }

        public virtual DbSet<TblUser> TblUsers { get; set; }

        public virtual DbSet<TblUserType> TblUserTypes { get; set; }

        public virtual DbSet<TblZone> TblZones { get; set; }

//        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//            => optionsBuilder.UseSqlServer("Data Source=Belal-2004;Initial Catalog=EstatelyDB;Integrated Security=True;Encrypt=True");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LKPPropertyHistoryType>(entity =>
            {
                entity.HasKey(e => e.HistoryTypeID).HasName("PK__LKPPrope__38069EDD6924C02B");
            });

            modelBuilder.Entity<TblAppointment>(entity =>
            {
                entity.HasOne(d => d.Property).WithMany(p => p.TblAppointments)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TblAppointments_TblProperties");

                entity.HasOne(d => d.Status).WithOne(p => p.TblAppointment)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TblAppointments_TblAppointmentStatus");
            });

            modelBuilder.Entity<TblBranch>(entity =>
            {
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblBranches_IsDeleted");
            });

            modelBuilder.Entity<TblBranchDepartment>(entity =>
            {
                entity.HasKey(e => e.BranchDepartmentID).HasName("PK__TblBranc__DE88E11B30E5A23E");

                entity.HasOne(d => d.Branch).WithMany(p => p.TblBranchDepartments)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblBranch__Branc__10566F31");

                entity.HasOne(d => d.Department).WithMany(p => p.TblBranchDepartments)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblBranch__Depar__114A936A");
            });

            modelBuilder.Entity<TblClientProfile>(entity =>
            {
                entity.Property(e => e.CreatedAt)
                    .HasDefaultValueSql("(getdate())")
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblClientProfiles");
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblClientProfiles_IsDeleted");

                entity.HasOne(d => d.User).WithOne(p => p.TblClientProfile)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TblClientProfiles_TblUsers");
            });

            modelBuilder.Entity<TblDeveloperProfile>(entity =>
            {
                entity.HasOne(d => d.User).WithOne(p => p.TblDeveloperProfile)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TblDeveloperProfiles_TblUsers");
            });

            modelBuilder.Entity<TblDocumentType>(entity =>
            {
                entity.HasKey(e => e.DocumentTypeID).HasName("PK__TblDocum__DBA390C11FF5415F");
            });

            modelBuilder.Entity<TblEmployee>(entity =>
            {
                entity.Property(e => e.HireDate)
                    .HasDefaultValueSql("(getdate())")
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblEmployees_DateTime");
                entity.Property(e => e.IsActive)
                    .HasDefaultValue(true)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblEmployees_isActive");

                entity.HasOne(d => d.Department).WithMany(p => p.TblEmployees).OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<TblEmployeeClient>(entity =>
            {
                entity.Property(e => e.AssignmentDate)
                    .HasDefaultValueSql("(getdate())")
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblEmployeeClients");
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblEmployeeClients_IsDeleted");
            });

            modelBuilder.Entity<TblFavorite>(entity =>
            {
                entity.Property(e => e.CreatedAt)
                    .HasDefaultValueSql("(getdate())")
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblFavorites");
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblFavorites_IsDeleted");
            });

            modelBuilder.Entity<TblProperty>(entity =>
            {
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblProperties_IsDeleted");
                entity.Property(e => e.ListingDate)
                    .HasDefaultValueSql("(getdate())")
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblProperties");

                entity.HasOne(d => d.Status).WithOne(p => p.TblProperty)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TblProperties_TblPropertyStatus");
            });

            modelBuilder.Entity<TblPropertyDocument>(entity =>
            {
                entity.HasKey(e => e.DocumentID).HasName("PK__TblPrope__1ABEEF6F9173FED6");

                entity.Property(e => e.UploadedAt).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.DocumentType).WithMany(p => p.TblPropertyDocuments)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblProper__Docum__214BF109");

                entity.HasOne(d => d.Property).WithMany(p => p.TblPropertyDocuments)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblProper__Prope__1F63A897");

                entity.HasOne(d => d.User).WithMany(p => p.TblPropertyDocuments).HasConstraintName("FK__TblProper__UserI__2057CCD0");
            });

            modelBuilder.Entity<TblPropertyHistory>(entity =>
            {
                entity.HasKey(e => e.HistoryID).HasName("PK__TblPrope__4D7B4ADDF535279D");

                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.HistoryType).WithMany(p => p.TblPropertyHistories)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblProper__Histo__19AACF41");

                entity.HasOne(d => d.Property).WithMany(p => p.TblPropertyHistories)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TblProper__Prope__17C286CF");

                entity.HasOne(d => d.User).WithMany(p => p.TblPropertyHistories).HasConstraintName("FK__TblProper__UserI__18B6AB08");
            });

            modelBuilder.Entity<TblUser>(entity =>
            {
                entity.Property(e => e.IsClient)
                    .HasDefaultValue(true)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblUsers_IsClient");
                entity.Property(e => e.IsDeleted)
                    .HasDefaultValue(false)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblUsers_IsDeleted");
                entity.Property(e => e.UserTypeID)
                    .HasDefaultValue(1)
                    .HasAnnotation("Relational:DefaultConstraintName", "DF_TblUsers_UserTypeID");

                entity.HasOne(d => d.UserType).WithMany(p => p.TblUsers).HasConstraintName("FK_TblUsers_TblUserType");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}